# Generated by Django 3.1.2 on 2020-10-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201016_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='color',
            field=models.CharField(max_length=255, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='conservation',
            field=models.CharField(max_length=255, verbose_name='Estado de conservación'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='internal_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Cód. interno'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_auxiliary',
            field=models.BooleanField(default=False, verbose_name='¿Es un bien auxiliar?'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='observation',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='pat_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Cód patrimonial'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Dimensiones'),
        ),
    ]
