# Generated by Django 3.1.2 on 2020-10-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201016_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_insurance',
            field=models.BooleanField(default=False, verbose_name='¿Tiene seguro?'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis',
            field=models.CharField(max_length=255, verbose_name='Chasis'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='conservation',
            field=models.CharField(max_length=255, verbose_name='Estado de conservación'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='cylinders',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Núm. de cilindros'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(max_length=255, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='internal_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Cód. interno'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='internal_plate',
            field=models.CharField(max_length=255, verbose_name='Placa interna'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='¿Está operativo?'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='motor_number',
            field=models.CharField(max_length=255, verbose_name='Núm. de motor'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='observation',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pat_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Cód patrimonial'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rod_plate',
            field=models.CharField(max_length=255, verbose_name='Placa de rodaje'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='soat',
            field=models.BooleanField(default=False, verbose_name='¿Tiene SOAT?'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=255, verbose_name='Año'),
        ),
    ]
