# Generated by Django 3.1.2 on 2020-10-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201016_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('AST', 'Bien'), ('AUX', 'Bien auxiliar'), ('OTH', 'Sobrantes')], default='AST', max_length=3),
        ),
        migrations.CreateModel(
            name='RealState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado en')),
                ('dependency', models.CharField(max_length=255, null=True, verbose_name='Dependency')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='')),
                ('urb', models.CharField(max_length=255, null=True, verbose_name='')),
                ('district', models.CharField(max_length=255, null=True, verbose_name='')),
                ('department', models.CharField(max_length=255, null=True, verbose_name='')),
                ('has_registry_info', models.BooleanField(default=True)),
                ('procedure_date', models.DateField(default=django.utils.timezone.now)),
                ('registry_area', models.CharField(max_length=255, null=True, verbose_name='')),
                ('property_state', models.CharField(choices=[('A', 'Alquilado'), ('P', 'Propio')], default='P', max_length=2)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('maintenance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('construction_date', models.DateField(default=django.utils.timezone.now)),
                ('persons', models.PositiveIntegerField(default=0)),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('built_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_planned_use', models.BooleanField(default=True)),
                ('is_corrected_use', models.BooleanField(default=True)),
                ('has_civil_defense', models.BooleanField(default=True)),
                ('last_civil_defense_inspection', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
