# Generated by Django 3.1.2 on 2020-10-18 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201018_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realstate',
            options={'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AlterField(
            model_name='realstate',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Área total del terreno'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='built_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Área total construida'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='construction_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Año de construcción del inmueble'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='department',
            field=models.CharField(max_length=255, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='dependency',
            field=models.CharField(max_length=255, null=True, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='Distrito/Provincia'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='has_civil_defense',
            field=models.BooleanField(default=True, verbose_name='Cuenta con Inspeccion de Defensa Civil'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='has_registry_info',
            field=models.BooleanField(default=True, verbose_name='Cuenta con saneamiento físico legal (información registral)'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='is_corrected_use',
            field=models.BooleanField(default=True, verbose_name='El local se usa para lo que fue construido'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='is_planned_use',
            field=models.BooleanField(default=True, verbose_name='Local planificado para ser usado como (Vivienda, almacen Base operativa, Oficina Administrativa, Taller, etc'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='last_civil_defense_inspection',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ultima fecha de Inspeccion de Defensa Civil'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='maintenance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto de mantenimeinto mensual'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='persons',
            field=models.PositiveIntegerField(default=0, verbose_name='Nñumero de personas que laboran'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='procedure_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio del trámite'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='registry_area',
            field=models.CharField(max_length=255, null=True, verbose_name='Area encargada del saneamiento físico legal'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto de alquiler mensual'),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='urb',
            field=models.CharField(max_length=255, null=True, verbose_name='Urbanización'),
        ),
    ]
